### ISSUE TITLE
AT-5: Start Building for Travel Plan 

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#105]
### Issue Tracking
This acceptance test is for #75.
See the test running [here](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-5).

#### Pre-requisite flow
* User taps on search box
* User searches for desired destination first (brings up the omnibox, the points below are all within the omnibox)

#### Main flow
* If location services are on and user is in a building, start location is automatically filled in (the building that the user is in)
* If location services are on and user is NOT in a building, start location is automatically filled in with their current location
* If location services are on and user is not in a building, they can override their current location by tapping on start location box and it can be filled in by tapping on a building or searching for it
* If location services are not on, start location is not automatically filled in. User must set start location (tap or search)

### Notes to PO
This is the distinction between the `Search Box` and `Omnibox`
![image.png](https://images.zenhubusercontent.com/5e161b263530c7e6cdf69a74/8cec3d2a-26aa-4656-a488-3843b8fdaa88)
The omnibox extends the search box, and includes extra travel customization.
![image.png](https://images.zenhubusercontent.com/5e161b263530c7e6cdf69a74/1f45d3d2-4d50-482f-89de-c835c3a3b3a5)

**Comment by mosaliza** [comment]
Passed.
