### ISSUE TITLE
AT-13: Accessible Indoor Navigation

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#108]
### Issue Tracking
This acceptance test is for #44.
See the test running [here](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-13).

### User Acceptance Flow
1. Once starting location and destination room are chosen, an accessible route is given to the user
2. Route must be the most accessible path, favouring ramps and elevators over stairs/escalators
3. Route is clear on the map
4. Navigation instructions are simple (such as: go up to 9th floor). No left/right turns.

**Comment by mosaliza** [comment]
![Screenshot_20200415-212852_Expo](https://user-images.githubusercontent.com/35632341/79404630-41750f00-7f60-11ea-8ba0-13d6b2252bfd.jpg)
![Screenshot_20200415-213021_Expo](https://user-images.githubusercontent.com/35632341/79404673-5ce01a00-7f60-11ea-9350-bb8de2b553c6.jpg)

**Comment by mosaliza** [comment]
Passed.
