### ISSUE TITLE
AT-12: Indoor Shortest Travel Route

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#109]
### Issue Tracking
This acceptance test is for #43.
See the test running [here](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-12).

### User Acceptance Flow
1. Once starting location and destination room are chosen, a route is given to the user
2. Route must be shortest and fastest path
3. Route is clear on the map
4. Navigation instructions are simple (such as: go up to 9th floor). No left/right turns, etc.

**Comment by mosaliza** [comment]
Some Navigation options are not enabled when selected.
There is no path shown neither for indoor nor outdoor.
The map only centers to current location.
The app has access to current location.

![Screenshot_20200415-212337_Expo](https://user-images.githubusercontent.com/35632341/79404468-c0b61300-7f5f-11ea-9c2f-c4fe0c3ed59d.jpg)
![Screenshot_20200415-212347_Expo](https://user-images.githubusercontent.com/35632341/79404473-c3186d00-7f5f-11ea-9ca9-a70c38273843.jpg)
![Screenshot_20200415-212310_Expo](https://user-images.githubusercontent.com/35632341/79404474-c4499a00-7f5f-11ea-8951-82a64b7f2d2d.jpg)

**Comment by RGPosadas** [comment]
@mosaliza 
Hello,

Please keep in mind this ticket, as well as AT-13, focus on `Indoor` implementation. 

Sorry we should have been more specific. Here are the rest of the information regarding this ticket:
1. There is no outdoor direction implementation. So setting your start location as `Current Location` and your destination location to a building will not render a travel route.
2. There exists mapping implementation, but only from indoor-to-indoor. If you set both your start and destination location to a room, you will see a travel route (example [GIF](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-12)).
3. Only the `Walking Man` and `Wheelchair` buttons are active. The car, bus, and shuttle bus buttons are not implemented and are currently just static UI elements.

**Comment by mosaliza** [comment]
Passed.
