### ISSUE TITLE
AT-6: Destination Building for Travel Plan

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#110]
### Issue Tracking
This acceptance test is for #73.
See the test running [here](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-6).

#### Search option
* User taps on search box
* User can search for a building to set as their desired destination (in search box focus)

#### Omnibox Tap/Search option
* User taps on search box
* User brings out the omnibox
* User taps on desired buliding to be autofilled in the destination location textbox
* User can also search for desired destination building  again in the omnibox

#### Tapping on Building option
* User taps on a building
* Sliding panel pops up with a button giving the user the option to travel to that building, which starts a travel plan

### Notes to PO
This is the distinction between the `Search Box` and `Omnibox`
![image.png](https://images.zenhubusercontent.com/5e161b263530c7e6cdf69a74/8cec3d2a-26aa-4656-a488-3843b8fdaa88)
The omnibox extends the search box, and includes extra travel customization.
![image.png](https://images.zenhubusercontent.com/5e161b263530c7e6cdf69a74/1f45d3d2-4d50-482f-89de-c835c3a3b3a5)

**Comment by mosaliza** [comment]
Passed.
