### ISSUE TITLE
US-3: Building location

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#16]
As a student, I want to know which building I am currently located in so that I know where I am situated.

**ACCEPTANCE CRITERIA:**
* Have a crosshair button that, when pressed, shows the building that I'm currently in
* Must match [Mockup](https://www.figma.com/file/1XeyBVJ2XyC6AHDHYwxvdG/WayFinder-SOEN390?node-id=46%3A2)
* Write unit tests and component tests

**USER FLOW ACCEPTANCE TEST:**
1. Press on the crosshair button
2. Map centers to the user location
3. User is informed if they are in a campus building or not
4. If user is in a building, then building info is shown

**Comment by cristian-aldea** [comment]
Progress Report: Implemented location services.

Remaining: Create a button that highlights the current building that the user is in

**Comment by RGPosadas** [comment]
UPDATE:
Not started
Blocked by waiting for #15 and #29 

Possible risk/uncertainty:
How do I calculate that a point is within a polygon?
^ Seems to be common
