### ISSUE TITLE
US-4: Additional campus building info

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#17]
As a student, I want to be able to see additional information for each campus building so that I can view information about them.

**ACCEPTANCE CRITERIA:**
* When pressing the overlay area of a building, a pop up should show with additional information about the building.
* As for the content of the pop-up, refer to the [Concordia Campus Map](http://www.concordia.ca/maps/sgw-campus.html)
* Overlay must change to another color when the building is selected.
* Must match [Mockup](https://www.figma.com/file/1XeyBVJ2XyC6AHDHYwxvdG/WayFinder-SOEN390?node-id=32%3A346)
* Respect the [Definition of Done](https://github.com/RGPosadas/WayFinder/wiki/Definition-of-Done)

**USER FLOW ACCEPTANCE TEST:**
1. Tap on a building
2. Tapped building changes colour to indicate that is the chosen building
3. A sliding panel will pop up from the bottom with basic info
4. You can swipe up on the sliding panel to give more info on a building
4.a. You can swipe down on the sliding panel to give less information
5. Close the sliding panel by clicking on the `x` button

**Comment by bit172** [comment]
Fellow teammate, may you please add the overlays as a separate component.

**Comment by JimLau49** [comment]
### **fixed**
Mockup appears as empty in the acceptance criteria

**Comment by RGPosadas** [comment]
UPDATE:
- Added panels
- When you click on them --> displays info
- Have to add services and departments in the data file

Problem:
- Always resets the map view when you tap on buildings --> reason why, when the component rerenders, the region is reset to when it was last updated. This should be changed so that it is set when we want it to be set.
- That's why it's disabled right now
- Did setting up a context help with the lag? --> no, but context helps access other resources that aren't direct children

**Comment by RGPosadas** [comment]
Reopened issue as previous merge did not fulfill all AC.

Missing AC:
* When pressing the overlay area of a building, a pop up should show with additional information about the building.
* As for the content of the pop-up, refer to the Concordia Campus Map
* Overlay must change to another color when the building is selected.

**Comment by cristian-aldea** [comment]
Update on progress:
* had to fix data structures
* had to breaking changes from develop
* Scrolling wasn't working on Android but was working on iOS
* 

What's left:
* Fix styling for text in panel
* remove swipe up for more info
* Put building color back to normal  when sliding panel is dismissed.

**Comment by cristian-aldea** [comment]
What's left: 
- having a location for every building, not just the bounding box. this is needed not just for the name marker, but for other future uses
- fixing bugs
- Check every building to make sure the information is right

Also, the data structure / design changes done for this issue will be ported to a task so that they can be made available in other tickets

**Comment by JimLau49** [comment]
> What's left:
> 
> * having a location for every building, not just the bounding box. this is needed not just for the name marker, but for other future uses
> * fixing bugs
> * Check every building to make sure the information is right
> 
> Also, the data structure / design changes done for this issue will be ported to a task so that they can be made available in other tickets

Repeating stuff on slack for formalities:

3rd point:
-SGW Campus mostly checked , will eyeball the rest just to see if some departments or services were not added for the smaller buildings / annexes. Big buildings are good to go.

-Loyola will need more checking

**Comment by leojrsilao** [comment]
What's updated:
- Completed Loyola campus buildings information
- Added a few missing building information in SGW
