### ISSUE TITLE
US-14: Indoor points of interest

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#19]
As a student, I want to see the indoor points of interest so that I may explore the building.

ACCEPTANCE CRITERIA:
* I should be able to see different Points of Interests (POIs) and floors inside the building.
* I should be able to control the floor I'm seeing on the map
* POIs should only show up on the indoor map if the floor they reside in is selected.
* POIs that are shown should be classes, bathrooms, elevators, stairs, etc.
* Must match [Mockup](https://www.figma.com/file/1XeyBVJ2XyC6AHDHYwxvdG/WayFinder-SOEN390?node-id=47%3A0)
* Respect the [Definition of Done](https://github.com/RGPosadas/WayFinder/wiki/Definition-of-Done)

**USER FLOW ACCEPTANCE TEST:**
Pre-requisite: user must be zoomed in enough on the map to enable indoor view
1. User is able to freely switch between floors using the floor picker
2. User sees different POIs on each floor
3. POIs seen are: classes, bathrooms ,elevators, stairs, etc

Blocks #18

**Comment by RGPosadas** [comment]
@cindyslittleplanet:
```
Summary of what I have done on US-14 before YS jumped in: 
Added the markers for points of interest for the 8th floor (9th floor doesn’t show up on Android, no indoor view shows up in Apple Maps so far - I believe that Leo and Jimmy’s US forced the app to go to Google Maps on iOS) 
Also, the colours of the pins don’t change colour in Android (they are all the basic red), however the pins are different colour on iOS - this is a minimal issue tho
Experimenting on how to hide/show markers depending on the level of zoom done by the user - Not going too well with that since there are not much resources online
The branch is up to date to Omar’s PR last night
But the toggle view and the markers are not implemented in the same view/map, so the screen is split into two if you run it (top with the toggle button and bottom with the markers - it kinda looks like a split screen), need to find a way to merge them together 
Problems in brief: 
Show/Hide markers depending on the level of zoom 
Merge toggle button and markers onto one map 
```

POST-HACKATHON UPDATE:
- Can discard work, just keep the markers for future reference as they will be useful in the future

CREATE TASKS FOR:
- indoor view for Loyola --> could be escalated to the spike if we are still unsure by Wednesday night
- floor toggle

THE UNKNOWNS:
- "Do we want a separate view? Or do we want the same view?" --> ideally it will be the same view
- Same view: having an overlay over Google Maps (through SVG using polygons and lines) --> how do we translate the coords of SVG to coords of real life?
- "How do we toggle floors?" --> https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md
- `showIndoorLevelPicker` --> markers between floors don't work on Android (but work on iOS)
- `setIndoorActiveLevelIndex` --> function that the component uses, but we are having issues calling and setting the floor, if we can just control it, it would make our life easier. If we can't then that's when we opt for a separate view
- "What if showIndoorLevelPicker isn't enough?" 
- How easy is it to display an SVG? 
- What was tried: tried to render the SVG on the display, not on the map through react-native-svg, had issues with that. It wasn't on the map - we were just able to get a basic SVG
- If we have a separate view: how do we locate people on that?
- Can we hide/display markers per floor?

**Comment by RGPosadas** [comment]
We need Hall POIs ASAP to unblock US-3

**Comment by cristian-aldea** [comment]
Tasks will be broken down as follows for this ticket:
* Adding a new Floor from SGW + the new POIs: @osahtout 
* Adding a new Floor from Loyola + the new POIs: @ys-lin 
* Making sure the floor picker works for existing and new floors: @TheGreatMarkus 
* Render markers conditionally based on the zoom level and current floor: @cindyslittleplanet
