### ISSUE TITLE
TASK-11: Setup Jest Unit Tests for US-1 and US-2

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#36]
As a developer, I want unit tests for US-1 and US-2 so that we can ensure quality code tested through Jest - and as a consequence, triggered on Travis as well.

Acceptance Criteria:
* Unit test exists for every component of US-1
* Unit test exists for every component of US-2

**Comment by JimLau49** [comment]
### **US-2 Snapshot done**

**US-1 CampusToggle** getting an error when running at test cause setRegion Cannot be null
![image](https://user-images.githubusercontent.com/35787279/75573565-1d4e8480-5a2b-11ea-96ee-10fbdeb95aeb.png)

![image](https://user-images.githubusercontent.com/35787279/75573623-36573580-5a2b-11ea-8ad7-1b5a2e8d4742.png)

**Comment by JimLau49** [comment]
![image](https://user-images.githubusercontent.com/35787279/75615898-d7bbb580-5b17-11ea-99ca-cfe229eb32bd.png)

@osahtout , line 3 changing null to anything else (ex: number) would be okay? Initializing it with Null doesnt allow it to be snapshot tested


![image](https://user-images.githubusercontent.com/35787279/75615958-852ec900-5b18-11ea-8d71-0ccde32dafdd.png)

**Comment by bit172** [comment]
Can you try using an empty object like this?  
`const RegionContext = React.createContext({})`

**Comment by JimLau49** [comment]
Yup this works thanks
