### ISSUE TITLE
TASK-17: implement ESLint

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#52]
As a developer, I want to implement ESLint so that it enforces coding standards and practices.

We currently do not have any JS/TS linters on our pre-commit. To keep on enabling good practices, we need to install ESLint: https://eslint.org/docs/user-guide/getting-started

**ACCEPTANCE CRITERIA**:
* Our JS/TypeScript code is linted
* Linters run on Travis as well
* There exists a section in the README on how to run ESLint

**Comment by JimLau49** [comment]
Running into an issue 
![image](https://user-images.githubusercontent.com/35787279/76991468-06ab9700-6920-11ea-866e-1b316855b6c5.png)

https://github.com/eslint/eslint/issues/12707
