### ISSUE TITLE
AT-1: Campus Toggle

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#64]
### Issue Tracking
This acceptance test is for #14.
See the test running [here](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-1).

### User Flow Acceptance Test
* On SGW button press, map is set to SGW campus view
* On Loyola button press, map is set to Loyola campus view

**Comment by mosaliza** [comment]
Passed.
