### ISSUE TITLE
AT-2: Distinguish Campus Buildings

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#65]
### Issue Tracking
This acceptance test is for #15.
See the test running [here](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-2).

### User Flow Acceptance Test
* All SGW buildings/annexes are present
* All Loyola building/annexes are present

**Comment by mosaliza** [comment]
Passed.
