### ISSUE TITLE
BUG-3: [iOS] The color of the building overlays are sometimes blue.

### ISSUE THREAD

**Issue by leojrsilao** [RGPosadas/SOEN390#68]
### Bug Description

The overlay of each building is sometimes colored blue. 

### Steps To Reproduce The Bug
```
> npm start
```
On application startup, the building overlays are just blue.

### What Is The Expected Result?

Every building overlay color is Concordia red.

### What Is The Actual Result?

Every building overlay color is blue. 

### Current Strategy
[ ] Fix it now
[ ] Fix it later
[x] Ignore it

### Additional Details/Screenshots

NOTE:
During #17, this issue was found and fixed on the physical iOS phones that were available to us. However, on slower iOS devices, it takes a while for the fix to appear. In this case, the bug can sometimes show up on our iOS simulators. 

#### Bug on iOS Simulator
![90345753_227852101738944_5503838295894786048_n](https://user-images.githubusercontent.com/43038259/77567032-ef7b2500-6e9c-11ea-811d-250dd43c4078.jpg)

#### Expected Result
![90787919_233587807690237_9000948449532706816_n](https://user-images.githubusercontent.com/43038259/77575587-23107c00-6eaa-11ea-9ba5-004b04a9bd7f.jpg)

**Comment by RGPosadas** [comment]
Closing since it only happens on emulator and the attempt to fix the bug during #17 worked on physical iOS devices.
