### ISSUE TITLE
TASK-20: Port tests to TypeScript

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/SOEN390#69]
As a developer, I want to port the non-TypeScript tests into TypeScript so that we may take advantage of the type checks.

**Comment by RGPosadas** [comment]
Some resources: https://github.com/solkaz/Detox/blob/master/docs/Guide.TypeScriptIntegrationJest.md

**Comment by RGPosadas** [comment]
Setting it to `wontfix` as it's not necessary for project completion.
