### ISSUE TITLE
AT-3: Building Location

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#76]
### Issue Tracking
This acceptance test is for #16.
See the test running [here](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-3).

### User Flow Acceptance Test
* Press on the crosshair button
* Map centers to the user location
* User is informed if they are in a campus building or not
* If user is in a building, then building info is shown

**Comment by mosaliza** [comment]
Passed.
