### ISSUE TITLE
AT-4: Additional Campus Building Info

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#77]
### Issue Tracking
This acceptance test is for #17.
See the test running [here](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-4).

### User Flow Acceptance Test
* Tap on a building
* Tapped building changes colour to indicate that is the chosen building
* A sliding panel will pop up from the bottom with basic info
* You can swipe up on the sliding panel to give more info on a building
* You can swipe down on the sliding panel to give less information
* Close the sliding panel by clicking on the `x` button

**Comment by mosaliza** [comment]
When the x button is clicked it does not close the sliding panel many times.
 Make it more sensitive to be closed properly.

**Comment by mosaliza** [comment]
Passed.
