### ISSUE TITLE
AT-14: Indoor Points of Interest

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#78]
### Issue Tracking
This acceptance test is for #19.
See the test running [here](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-14).

### User Flow Acceptance Test
Pre-requisite: user must be zoomed in enough on the map to enable indoor view
* User is able to freely switch between floors using the floor picker
* User sees different POIs on each floor
* POIs seen are: classes, bathrooms ,elevators, stairs, etc

**Comment by mosaliza** [comment]
The floor picker should only be seen when the user gets close enough to see the indoor view (not before that).

**Comment by JimLau49** [comment]
@mosaliza Good evening PO,

Could you please provide the steps to reproduce this issue and give more information about the issue?

**Comment by mosaliza** [comment]
Yes. The problem is that as you try to zoom in the floor picker becomes
visible  even before the indoor view is shown.

Sadegh

**Comment by RGPosadas** [comment]
Passed by the PO via email.
![image](https://user-images.githubusercontent.com/33991121/78801509-ce313300-798a-11ea-9474-9b3904756705.png)
