### ISSUE TITLE
AT-11: Search Start and Destination Room

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#79]
### Issue Tracking
This acceptance test is for #18.
See the test running [here](https://github.com/RGPosadas/WayFinder/wiki/Acceptance-Tests-GIFs#us-11).

**USER FLOW ACCEPTANCE TEST:**
1. Tap on the search bar
2. User can search or tap on a point of interest to set it as the destination
3. If location services are on, `starting location` is filled with the user's current location
3.a. If location services are not on, `starting location` is filled in by the user. First tap on the top text box and then either search for a POI or tap on a POI on the map
4. Once the start and end locations are set, press on the now visible start travel button on the bottom right
5. Markers for the start and end location will be shown on the map

**Comment by mosaliza** [comment]
Passed.
